# Generated by Django 6.0.6 on 2026-07-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('organizer', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('online', 'Online'), ('in_person', 'In-person'), ('hybrid', 'Hybrid')], default='online', max_length=20)),
                ('category', models.CharField(choices=[('ai', 'AI'), ('web3', 'Web3'), ('climate', 'Climate'), ('health', 'Health'), ('fintech', 'Fintech'), ('gaming', 'Gaming'), ('student', 'Student'), ('beginner', 'Beginner'), ('iot', 'IoT'), ('ar_vr', 'AR/VR'), ('edtech', 'EdTech'), ('other', 'Other')], default='other', max_length=20)),
                ('prize_pool', models.CharField(blank=True, default='', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('apply_url', models.URLField()),
                ('description', models.TextField(blank=True, default='')),
                ('cover_image', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
