# Generated by Django 6.0.6 on 2026-07-02 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('company_logo', models.URLField(blank=True, default='')),
                ('company_url', models.URLField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('remote', models.BooleanField(default=True)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_currency', models.CharField(default='USD', max_length=3)),
                ('experience_level', models.CharField(blank=True, choices=[('fresher', 'Fresher / Intern'), ('junior', 'Junior'), ('mid', 'Mid-level'), ('senior', 'Senior'), ('lead', 'Lead / Manager+')], default='', max_length=20)),
                ('category', models.CharField(blank=True, choices=[('engineering', 'Engineering'), ('design', 'Design'), ('product', 'Product'), ('data_ai', 'Data & AI'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('operations', 'Operations')], default='', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('apply_url', models.URLField()),
                ('source_url', models.URLField(blank=True, default='')),
                ('source_company', models.CharField(blank=True, default='', max_length=255)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', '-posted_at', '-created_at'],
                'indexes': [models.Index(fields=['category', 'experience_level', 'is_active'], name='jobs_job_categor_0f9292_idx'), models.Index(fields=['is_active', 'expires_at'], name='jobs_job_is_acti_0d745b_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'job')},
            },
        ),
    ]
