# Generated by Django 6.0.6 on 2026-07-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_type', models.CharField(default='full', max_length=50)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=20)),
                ('jobs_created', models.IntegerField(default=0)),
                ('hackathons_created', models.IntegerField(default=0)),
                ('jobs_expired', models.IntegerField(default=0)),
                ('hackathons_expired', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
