# Generated by Django 6.0.6 on 2026-07-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author_name',
            field=models.CharField(default='Jobs24X7 Team', max_length=100),
        ),
    ]
